import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import localFont from 'next/font/local'
import Image from 'next/image'
import sidebar from '@/public/images/bg-sidebar-desktop.svg'

const inter = Inter({ subsets: ['latin'] })
const myFont = localFont({
  src: [
    { path: '../public/fonts/Ubuntu-Regular.ttf', weight: '400', style: 'noraml' },
    { path: '../public/fonts/Ubuntu-Medium.ttf', weight: '500', style: 'noraml' },
    { path: '../public/fonts/Ubuntu-Bold.ttf', weight: '600', style: 'noraml' },
  ],
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Step = ({ step, title, active = false }) => {
  const activeClass = active ? 'bg-sky-200 text-black' : 'text-white'
  return (
    <div class="flex flex-row items-center uppercase mb-4">
      <p
        class={`mr-4 flex h-8 w-8 items-center justify-center rounded-full border border-white  p-1 text-center text-xs font-semibold  ${activeClass}`}>
        <span>{step}</span>
      </p>
      <div class="flex flex-col">
        <p class="text-[10px] text-slate-300">step {step}</p>
        <p class="text-[13px] font-[500]">{title}</p>
      </div>
    </div>
  )
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <div class="flex h-screen items-center justify-center bg-blue-100 py-[10%]">
          <div class=" h-[400px] w-[700px] grid grid-cols-12 bg-white p-2 rounded-lg">
            <div
              class="relative col-span-4 rounded-lg bg-cover p-5 text-white"
              style={{
                'background-image':
                  "url('https://github.com/ricky4473/Multi-stepform/raw/main/public/images/bg-sidebar-desktop.svg')",
              }}>
              {[
                { step: 1, title: 'your info' },
                { step: 2, title: 'Select plan' },
                { step: 3, title: 'add-ons' },
                { step: 4, title: 'summary' },
              ].map((item, index) => {
                return <Step key={index} title={item.title} step={item.step} />
              })}
            </div>
            <div class="col-span-8 px-9 py-2 flex flex-col justify-between text-sky-800">
              {children}{' '}
              <div class="flex flex-row justify-between">
                <button class="text-slate-400 text-xs hover:text-blue-900">Go Back</button>

                <button class="bg-blue-900 text-white text-xs px-3 py-2 rounded-md">
                  Next Step
                </button>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
