//@ts-nocheck
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import localFont from 'next/font/local'

const inter = Inter({ subsets: ['latin'] })
const myFont = localFont({
  src: [
    { path: '../public/fonts/Ubuntu-Regular.ttf', weight: '400', style: 'noraml' },
    { path: '../public/fonts/Ubuntu-Medium.ttf', weight: '500', style: 'noraml' },
    { path: '../public/fonts/Ubuntu-Bold.ttf', weight: '600', style: 'noraml' },
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  )
}
