import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Image from "next/image";
import sidebar from "@/public/images/bg-sidebar-desktop.svg";

const inter = Inter({ subsets: ["latin"] });
const myFont = localFont({ src: "../public/fonts/Ubuntu-Bold.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <div class="bg-blue-100 h-screen flex justify-center items-center px-[20%] py-[10%] ">
          <div class=" grid grid-cols-12  bg-white  w-[700px] h-[400px]">
            <div
              class="col-span-4 relative p-2 w-full h-full text-white"
              style={{ "background-image": `url(${sidebar.src})` }}
            >
              <p>Your info</p>
              <p>Select plan</p>
              <p>Add-ons</p>
              <p>summary</p>
            </div>
            <div class="col-span-8">hello</div>
          </div>
        </div>
      </body>
    </html>
  );
}
